// <auto-generated />
using System;
using LogicaDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaDatos.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20250410171055_asdfgfg")]
    partial class asdfgfg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.EmpleadoTurnoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("EmpleadoTurnoServicios");
                });

            modelBuilder.Entity("LogicaNegocio.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("LogicaNegocio.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("Multitask")
                        .HasColumnType("bit");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("TipoId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("LogicaNegocio.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("LogicaNegocio.TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("TipoServicios");
                });

            modelBuilder.Entity("LogicaNegocio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Usr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.Admin", b =>
                {
                    b.HasBaseType("LogicaNegocio.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("LogicaNegocio.Cliente", b =>
                {
                    b.HasBaseType("LogicaNegocio.Usuario");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("LogicaNegocio.Empleado", b =>
                {
                    b.HasBaseType("LogicaNegocio.Usuario");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.HasIndex("NegocioId");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("LogicaNegocio.Negocio", b =>
                {
                    b.HasBaseType("LogicaNegocio.Usuario");

                    b.HasDiscriminator().HasValue("Negocio");
                });

            modelBuilder.Entity("LogicaNegocio.EmpleadoTurnoServicio", b =>
                {
                    b.HasOne("LogicaNegocio.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Reserva", "Reserva")
                        .WithMany("EmpleadosTurnos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LogicaNegocio.Reserva", b =>
                {
                    b.HasOne("LogicaNegocio.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LogicaNegocio.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("LogicaNegocio.Servicio", b =>
                {
                    b.HasOne("LogicaNegocio.Negocio", "Negocio")
                        .WithMany("Servicios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.TipoServicio", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("LogicaNegocio.Sucursal", b =>
                {
                    b.HasOne("LogicaNegocio.Negocio", "Negocio")
                        .WithMany("Sucursales")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LogicaNegocio.HorarioDia", "HorariosAtencion", b1 =>
                        {
                            b1.Property<int>("SucursalId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Dia")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time");

                            b1.HasKey("SucursalId", "Id");

                            b1.ToTable("Sucursales_HorariosAtencion");

                            b1.WithOwner()
                                .HasForeignKey("SucursalId");
                        });

                    b.Navigation("HorariosAtencion");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("LogicaNegocio.TipoServicio", b =>
                {
                    b.HasOne("LogicaNegocio.Negocio", "Negocio")
                        .WithMany("TipoServicios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("LogicaNegocio.Empleado", b =>
                {
                    b.HasOne("LogicaNegocio.Negocio", "Negocio")
                        .WithMany("Empleados")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("LogicaNegocio.HorarioDia", "HorariosJornada", b1 =>
                        {
                            b1.Property<int>("EmpleadoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Dia")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time");

                            b1.HasKey("EmpleadoId", "Id");

                            b1.ToTable("Usuarios_HorariosJornada");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.Navigation("HorariosJornada");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("LogicaNegocio.Reserva", b =>
                {
                    b.Navigation("EmpleadosTurnos");
                });

            modelBuilder.Entity("LogicaNegocio.Negocio", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Servicios");

                    b.Navigation("Sucursales");

                    b.Navigation("TipoServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
